spotify:
  clientId: ""
  clientSecret: ""
  tokenLocation: database
server:
  host: 0.0.0.0
  port: 8080
database:
  driver: postgres
  source: "postgres://postgres:root@0.0.0.0:5432/spotify_db?sslmode=disable"
