spotify:
  clientId: dwa
  clientSecret: dwa
  tokenFile: token.json
server:
  host: localhost
  port: 8080
database:
  driver: postgres
  source: "postgres://postgres:root@0.0.0.0:5432/spotify_db?sslmode=disable"
