services:
  postgres:
    container_name: spotify-postgres
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spotify_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: no

  pgadmin:
    container_name: spotify-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: no

volumes:
  postgres-data:
